# Generated by Django 5.2.1 on 2025-05-21 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0004_userdetails_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to='profile_picture/'),
        ),
    ]
