# Generated by Django 5.2.1 on 2025-05-21 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0005_alter_userdetails_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='crud_app.user'),
        ),
    ]
